version: '3.9'

x-logging: &default-logging
  options:
    max-size: "16m"
    max-file: "5"
  driver: json-file

services:
  myimage:
    container_name: mycontainer
    hostname: yourcontainer
    build:
      context: ./
      dockerfile: Dockerfile
    logging: *default-logging
    ports:
      - 8080:8080

  nginx:
    container_name: mynginx
    image: docker.io/library/nginx:stable
    logging: *default-logging
    ports:
      - 8081:80
    restart: unless-stopped
    hostname: yournginx
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
